### ISSUE TITLE
Example Code not working

### ISSUE THREAD

**Issue by bl0cksb3rg** [pitermcflebor/pmc-callbacks#5]
Hi!

When i trigger a server event sync / async i dont get any result from server.
I added a debug message in my server event and its getting called so only the result is not working. Can you help me with this?

![image](https://user-images.githubusercontent.com/56239171/135162565-6d4887c6-b6d6-4eeb-9b21-dcb9dd27b111.png)

![image](https://user-images.githubusercontent.com/56239171/135162607-09059e80-16fa-41c4-a8d9-7f79a458ef60.png)

![image](https://user-images.githubusercontent.com/56239171/135162665-c23140b0-46ba-49d7-94ab-e02e348f6f42.png)

Best Regards,
Paul!

**Comment by pitermcflebor** [comment]
Hi, sorry I couldn't test everything correctly.
I will take a look!

**Comment by bl0cksb3rg** [comment]
Okay! Thank you very much.

**Comment by Twiitchter** [comment]
I could be wrong here, but perhaps it's line 93 being different from line 211?

The event name is different?

**Comment by pitermcflebor** [comment]
@bl0cksb3rg I found the issue, check the last commit and take a look if it works!

**Comment by bl0cksb3rg** [comment]
Got result, but now I got this error. Thank you! Can you fix this error also?

![image](https://user-images.githubusercontent.com/56239171/135441914-8e8c6baf-897c-41ac-9285-5f5898580ed4.png)

**Comment by pitermcflebor** [comment]
Okay, sorry I will take a look again on my free time.

**Comment by Twiitchter** [comment]
On Server, Find: (was line 93)
`RegisterNetEvent(('pmc__callback:retval:%s:%s:%s')`

On Client, Find: (was line 211)
`TriggerServerEvent(('pmc__callback_retval:%s:%s:%s')`

The names are different, Does this matter?

**Comment by Twiitchter** [comment]
@bl0cksb3rg I did some playing around and made a PR for @pitermcflebor, The error on the local eventData is due to it being null, as technically the variable isn't declared inside the RegisterNetEvent.

This basically meant the event wasn't being removed after being used.
I also corrected the typo I've mentioned above.

The work around I did was waiting for the promise to return via the await, then triggering the removal of the event.
Seems to be working like a charm after that!
Much love to @pitermcflebor.
